import { test, expect } from '@playwright/test'

async function login(page: import('@playwright/test').Page) {
  await page.goto('/login')
  await page.getByLabel('Email').fill(process.env.E2E_EMAIL ?? '')
  await page.getByLabel('Password').fill(process.env.E2E_PASSWORD ?? '')
  await page.getByRole('button', { name: 'Accedi' }).click()
  await expect(page).toHaveURL(/\/app/)
}

async function setCode(page: import('@playwright/test').Page, code: string) {
  await page.locator('.monaco-editor .view-lines').click()
  await page.keyboard.press('Control+A')
  await page.keyboard.insertText(code)
  await expect(page.locator('.monaco-editor .view-lines')).toContainText(code.split('\n')[0])
}

test('login, programma, Python e input', async ({ page }) => {
  await page.goto('/login')
  await expect(page.getByRole('heading', { name: 'Bentornato.' })).toBeVisible()
  await page.getByLabel('Email').fill(process.env.E2E_EMAIL ?? '')
  await page.getByLabel('Password').fill(process.env.E2E_PASSWORD ?? '')
  await page.getByRole('button', { name: 'Accedi' }).click()
  await expect(page).toHaveURL(/\/app/)
  await expect.poll(() => page.evaluate(() => crossOriginIsolated)).toBe(true)
  await page.getByRole('button', { name: 'Nuovo programma' }).click()
  await expect(page).toHaveURL(/\/app\/[^/]+/)
  await expect(page.getByRole('button', { name: 'START' })).toBeEnabled({ timeout: 60_000 })
  await page.getByRole('button', { name: 'START' }).click()
  await expect(page.getByTestId('output').getByText('Ciao, Emipy!')).toBeVisible()
  await setCode(page, 'name = input("Nome? ")\nprint("Ciao " + name)')
  await page.getByRole('button', { name: 'START' }).click()
  await expect(page.getByLabel('Input programma')).toBeEnabled()
  await page.getByLabel('Input programma').fill('Ada')
  await page.getByRole('button', { name: 'Invia' }).click()
  await expect(page.getByTestId('output').getByText('Ciao Ada')).toBeVisible()
  await expect(page.getByText('Salvato')).toBeVisible()
})

test('input multiplo, autosave e STOP su loop', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: 'Nuovo programma' }).click()
  await expect(page.getByRole('button', { name: 'START' })).toBeEnabled({ timeout: 60_000 })
  await setCode(page, 'a = input("A? ")\nb = input("B? ")\nprint(a + " / " + b)')
  await expect(page.getByText('Salvato')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'START' })).toBeEnabled({ timeout: 60_000 })
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('a = input')
  await page.getByRole('button', { name: 'START' }).click()
  await expect(page.getByLabel('Input programma')).toBeEnabled()
  await page.getByLabel('Input programma').fill('uno')
  await page.getByRole('button', { name: 'Invia' }).click()
  await expect(page.getByLabel('Input programma')).toBeEnabled()
  await page.getByLabel('Input programma').fill('due')
  await page.getByRole('button', { name: 'Invia' }).click()
  await expect(page.locator('.output-scroll')).toContainText('uno / due')
  await setCode(page, 'while True:\n    pass')
  await page.getByRole('button', { name: 'START' }).click()
  await expect(page.getByRole('button', { name: 'STOP' })).toBeVisible()
  await page.getByRole('button', { name: 'STOP' }).click()
  await expect(page.getByRole('button', { name: 'START' })).toBeEnabled({ timeout: 60_000 })
  await setCode(page, 'print("Dopo STOP")')
  await page.getByRole('button', { name: 'START' }).click()
  await expect(page.locator('.output-scroll')).toContainText('Dopo STOP')
})

test('STOP durante input, rinomina ed elimina', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: 'Nuovo programma' }).click()
  await expect(page).toHaveURL(/\/app\/[^/]+/)
  const createdUrl = page.url()
  await expect(page.getByRole('button', { name: 'START' })).toBeEnabled({ timeout: 60_000 })
  await setCode(page, 'input("Attendo")')
  await page.getByRole('button', { name: 'START' }).click()
  await expect(page.getByLabel('Input programma')).toBeEnabled()
  await page.getByRole('button', { name: 'STOP' }).click()
  await expect(page.getByRole('button', { name: 'START' })).toBeEnabled({ timeout: 60_000 })
  await page.getByRole('button', { name: 'Senza titolo' }).first().click()
  await page.getByLabel('Nome programma').fill('Prova Emipy')
  await page.getByRole('button', { name: 'Salva' }).click()
  await expect(page.getByRole('button', { name: 'Prova Emipy' }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Azioni programma' }).click()
  await page.getByRole('menuitem', { name: 'Elimina' }).click()
  await page.getByRole('button', { name: 'Elimina' }).click()
  await expect(page).not.toHaveURL(createdUrl)
})

test('stderr, errore di sintassi ed errore runtime', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: 'Nuovo programma' }).click()
  await expect(page.getByRole('button', { name: 'START' })).toBeEnabled({ timeout: 60_000 })
  await setCode(page, 'import sys\nprint("avviso", file=sys.stderr)')
  await page.getByRole('button', { name: 'START' }).click()
  await expect(page.locator('.output-scroll .text-destructive')).toContainText('avviso')
  await setCode(page, 'if True print("no")')
  await page.getByRole('button', { name: 'START' }).click()
  await expect(page.locator('.output-scroll .text-destructive')).toContainText('SyntaxError')
  await setCode(page, 'raise ValueError("errore test")')
  await page.getByRole('button', { name: 'START' }).click()
  await expect(page.locator('.output-scroll .text-destructive')).toContainText('ValueError: errore test')
})

test('admin e registrazione pubblica chiusa', async ({ page, request }) => {
  const signUp = await request.post('/api/auth/sign-up/email', { data: { name: 'Intruso', email: 'intruso@example.test', password: 'Something123!' } })
  expect(signUp.ok()).toBe(false)
  await page.goto('/login')
  await page.getByLabel('Email').fill(process.env.E2E_EMAIL ?? '')
  await page.getByLabel('Password').fill(process.env.E2E_PASSWORD ?? '')
  await page.getByRole('button', { name: 'Accedi' }).click()
  await expect(page).toHaveURL(/\/app/)
  await page.goto('/admin')
  await expect(page.getByRole('heading', { name: 'Utenti' })).toBeVisible()
})

test('admin crea, sospende, resetta ed elimina un utente', async ({ page, browser }) => {
  await login(page)
  await page.goto('/admin')
  await expect(page.getByRole('row').filter({ hasText: process.env.E2E_EMAIL ?? '' })).toBeVisible()
  const email = `e2e-${Date.now()}@example.test`
  await page.getByRole('button', { name: 'Nuovo utente' }).click()
  await page.getByLabel('Nome').fill('Utente Test')
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password iniziale').fill('PrimaPassword123!')
  await page.getByRole('button', { name: 'Crea utente' }).click()
  const row = page.getByRole('row').filter({ hasText: email })
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: 'Sospendi' }).click()
  await expect(row).toContainText('Sospeso')
  await row.getByRole('button', { name: 'Riattiva' }).click()
  await expect(row).toContainText('Attivo')
  await row.getByRole('button', { name: 'Password' }).click()
  await page.getByRole('dialog', { name: 'Nuova password' }).locator('input[type=password]').fill('NuovaPassword123!')
  await page.getByRole('button', { name: 'Aggiorna password' }).click()
  const other = await browser.newContext()
  const userPage = await other.newPage()
  await userPage.goto('/login')
  await userPage.getByLabel('Email').fill(email)
  await userPage.getByLabel('Password').fill('NuovaPassword123!')
  await userPage.getByRole('button', { name: 'Accedi' }).click()
  await expect(userPage).toHaveURL(/\/app/)
  await userPage.getByRole('button', { name: 'Nuovo programma' }).click()
  await expect(userPage).toHaveURL(/\/app\/[^/]+/)
  const privateProgram = userPage.url()
  await page.goto(privateProgram)
  await expect(page.getByText('Programma non trovato')).toBeVisible()
  await page.goto('/admin')
  await expect(page.getByRole('row').filter({ hasText: email })).toBeVisible()
  await userPage.goto('/admin')
  await expect(userPage).toHaveURL(/\/app/)
  await other.close()
  await row.getByRole('button', { name: 'Elimina' }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: 'Elimina' }).click()
  await expect(row).toHaveCount(0)
})
