/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTutorRouteImport } from './routes/api/tutor'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppProgramIdRouteImport } from './routes/app/$programId'
import { Route as AppLibraryRouteImport } from './routes/app/library'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppCoursesIndexRouteImport } from './routes/app/courses/index'
import { Route as AppPlaygroundProgramIdRouteImport } from './routes/app/playground/$programId'
import { Route as AppCoursesCourseIdIndexRouteImport } from './routes/app/courses/$courseId/index'
import { Route as AppCoursesCourseIdLessonIdIndexRouteImport } from './routes/app/courses/$courseId/$lessonId/index'
import { Route as AppCoursesCourseIdLessonIdProgramIdRouteImport } from './routes/app/courses/$courseId/$lessonId/$programId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProgramIdRoute = AppProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlaygroundProgramIdRoute = AppPlaygroundProgramIdRouteImport.update({
  id: '/playground/$programId',
  path: '/playground/$programId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesCourseIdIndexRoute = AppCoursesCourseIdIndexRouteImport.update({
  id: '/courses/$courseId/',
  path: '/courses/$courseId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoursesCourseIdLessonIdIndexRoute =
  AppCoursesCourseIdLessonIdIndexRouteImport.update({
    id: '/courses/$courseId/$lessonId/',
    path: '/courses/$courseId/$lessonId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCoursesCourseIdLessonIdProgramIdRoute =
  AppCoursesCourseIdLessonIdProgramIdRouteImport.update({
    id: '/courses/$courseId/$lessonId/$programId',
    path: '/courses/$courseId/$lessonId/$programId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/tutor': typeof ApiTutorRoute
  '/app/$programId': typeof AppProgramIdRoute
  '/app/library': typeof AppLibraryRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/playground/$programId': typeof AppPlaygroundProgramIdRoute
  '/app/courses/': typeof AppCoursesIndexRoute
  '/app/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/app/courses/$courseId/$lessonId/$programId': typeof AppCoursesCourseIdLessonIdProgramIdRoute
  '/app/courses/$courseId/$lessonId/': typeof AppCoursesCourseIdLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/tutor': typeof ApiTutorRoute
  '/app/$programId': typeof AppProgramIdRoute
  '/app/library': typeof AppLibraryRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/playground/$programId': typeof AppPlaygroundProgramIdRoute
  '/app/courses': typeof AppCoursesIndexRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdIndexRoute
  '/app/courses/$courseId/$lessonId/$programId': typeof AppCoursesCourseIdLessonIdProgramIdRoute
  '/app/courses/$courseId/$lessonId': typeof AppCoursesCourseIdLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/tutor': typeof ApiTutorRoute
  '/app/$programId': typeof AppProgramIdRoute
  '/app/library': typeof AppLibraryRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/playground/$programId': typeof AppPlaygroundProgramIdRoute
  '/app/courses/': typeof AppCoursesIndexRoute
  '/app/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/app/courses/$courseId/$lessonId/$programId': typeof AppCoursesCourseIdLessonIdProgramIdRoute
  '/app/courses/$courseId/$lessonId/': typeof AppCoursesCourseIdLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/admin'
    | '/login'
    | '/api/health'
    | '/api/tutor'
    | '/app/$programId'
    | '/app/library'
    | '/app/'
    | '/api/auth/$'
    | '/app/playground/$programId'
    | '/app/courses/'
    | '/app/courses/$courseId/'
    | '/app/courses/$courseId/$lessonId/$programId'
    | '/app/courses/$courseId/$lessonId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/api/health'
    | '/api/tutor'
    | '/app/$programId'
    | '/app/library'
    | '/app'
    | '/api/auth/$'
    | '/app/playground/$programId'
    | '/app/courses'
    | '/app/courses/$courseId'
    | '/app/courses/$courseId/$lessonId/$programId'
    | '/app/courses/$courseId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/admin'
    | '/login'
    | '/api/health'
    | '/api/tutor'
    | '/app/$programId'
    | '/app/library'
    | '/app/'
    | '/api/auth/$'
    | '/app/playground/$programId'
    | '/app/courses/'
    | '/app/courses/$courseId/'
    | '/app/courses/$courseId/$lessonId/$programId'
    | '/app/courses/$courseId/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTutorRoute: typeof ApiTutorRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$programId': {
      id: '/app/$programId'
      path: '/$programId'
      fullPath: '/app/$programId'
      preLoaderRoute: typeof AppProgramIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/courses/': {
      id: '/app/courses/'
      path: '/courses'
      fullPath: '/app/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/playground/$programId': {
      id: '/app/playground/$programId'
      path: '/playground/$programId'
      fullPath: '/app/playground/$programId'
      preLoaderRoute: typeof AppPlaygroundProgramIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/courses/$courseId/': {
      id: '/app/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/app/courses/$courseId/'
      preLoaderRoute: typeof AppCoursesCourseIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/courses/$courseId/$lessonId/': {
      id: '/app/courses/$courseId/$lessonId/'
      path: '/courses/$courseId/$lessonId'
      fullPath: '/app/courses/$courseId/$lessonId/'
      preLoaderRoute: typeof AppCoursesCourseIdLessonIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/courses/$courseId/$lessonId/$programId': {
      id: '/app/courses/$courseId/$lessonId/$programId'
      path: '/courses/$courseId/$lessonId/$programId'
      fullPath: '/app/courses/$courseId/$lessonId/$programId'
      preLoaderRoute: typeof AppCoursesCourseIdLessonIdProgramIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppProgramIdRoute: typeof AppProgramIdRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPlaygroundProgramIdRoute: typeof AppPlaygroundProgramIdRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppCoursesCourseIdIndexRoute: typeof AppCoursesCourseIdIndexRoute
  AppCoursesCourseIdLessonIdProgramIdRoute: typeof AppCoursesCourseIdLessonIdProgramIdRoute
  AppCoursesCourseIdLessonIdIndexRoute: typeof AppCoursesCourseIdLessonIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProgramIdRoute: AppProgramIdRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppIndexRoute: AppIndexRoute,
  AppPlaygroundProgramIdRoute: AppPlaygroundProgramIdRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppCoursesCourseIdIndexRoute: AppCoursesCourseIdIndexRoute,
  AppCoursesCourseIdLessonIdProgramIdRoute:
    AppCoursesCourseIdLessonIdProgramIdRoute,
  AppCoursesCourseIdLessonIdIndexRoute: AppCoursesCourseIdLessonIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTutorRoute: ApiTutorRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
